#!/usr/bin/env bash
# Script to install and configure Nginx
sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx start
