#!/usr/bin/env bash
# Script to install and configure Nginx
apt install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx reload
