#!/usr/bin/env bash
# Script to configure nginx to redirect a page

# Update system and install nginx
sudo apt -y update && sudo apt -y upgrade
sudo apt install nginx
sudo service nginx start

# Snippet to append
sample='\\n\tlocation /redirect_me {\n\t\treturn 301;\n\t}'

# Path to config file
path_nginx="/etc/nginx/sites-enabled/default"

sed "/server_name _;/a $sample" "$path_nginx" > default.temp.conf.bak
mv default.temp.conf.bak "$path_nginx"
service nginx reload
