#!/usr/bin/env bash
# Script to configure a Nginx server to have a custom 404 page with a string

apt -y update && apt -y upgrade
apt -y install nginx
service nginx start

# Snippet to append
sample='\\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}'

# Path to config file
path_404="/etc/nginx/sites-enabled/default"

sed "/server_name _;/a $sample" "$path_404" > def.test.conf.bq
mv def.test.conf.bq "$path_404"

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

# Restart Nginx and reload config file
service nginx restart
service nginx reload
