#!/usr/bin/env bash
# Script to install and configure HAProxy

# Update system and install haproxy
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get -y update
apt-get -y install haproxy=2.9.\*

# Path to config file
path_hap="/etc/haproxy/haproxy.cfg"
path_def="/etc/default/haproxy"

# Make a config backup if it doesn't exist
if [ ! -f "$path_hap".orig ]; then
    cp "$path_hap" "path_hap".orig
    echo "Haproxy Backup created"
fi

# Make a default backup if it doesnt exit
if [ ! -f "$path_def".orig ]; then
    cp "$path_def" "path_def".orig
    echo "Haproxy Default Backup created"
fi

# Snippet to append
echo "frontend http
     bind *:80
     mode http
     default_backend nginx_webservers

backend nginx_webservers
	balance roundrobin
	server 212504-web-01	54.87.177.138:80 check
	server 212504-web-02	52.3.220.168:80 check" >> "$path_hap"

echo "ENABLED=1" >> "$path_def"

service haproxy start
