#!/usr/bin/env bash
# Script that displays the content of the file /etc/passwd

INFILE="/etc/passwd"

while read -r LINE; do
    result=$(echo "$LINE" | cut -d ":" -f 1,3,6)
    echo "$result"
done < "$INFILE"
