#!/usr/bin/env bash
# Script that tells the story of passwd

INFILE="/etc/passwd"

while IFS=":" read -r -a FIELDS; do
    echo "The user ${FIELDS[0]} is part of the ${FIELDS[3]} gang, lives in ${FIELDS[5]} and rides ${FIELDS[6]}. ${FIELDS[2]}'s place is protected by the passcode ${FIELDS[1]}, more info about the user here: ${FIELDS[4]}"
done < "$INFILE"
